### PR TITLE
Ifara

### LINKED ISSUE #6: Integrate Database into application
# Proposed Feature
Integrate Database into application

# Why is this important?
Facilitates storage and retrieval of solutions, solution providers information and user information.

# Additional Context
Adopt relational database for main db functionalities and Redis at caching layer.

### PR DESCRIPTION
**Pull request by farajayh**
## Description
Creation of API endpoints for registration and login.
Creation of the database schema for the application

Fixes #6 #7 #8

## How Has This Been Tested?
The register and login API endpoints were tested using Postman

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added necessary inline code documentation
- [X] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by farajayh — COMMENTED** [review]
All code changes have been reviewed by me and deemed okay.

**Review by farajayh — COMMENTED** [review]
All code changes have been reviewed by me and are deemed okay

**Review by thesamtj — DISMISSED** [review]
All code changes have been reviewed by me and deemed okay.

**Review by foreign1 — APPROVED** [review]
Looks good to me. Great work Josh.

**Review by thesamtj — APPROVED** [review]
Good to go

**Pull request merged**
